/**:
  ros__parameters:
    wheel_radius: 0.2286 # YDRE 輪胎尺寸 18 x 8.50–8.00。輪胎直徑為 18 英寸，所以半徑為 18 / 2 = 9 英寸。9 英寸 * 0.0254 m/inch = 0.2286 m。
    wheel_width: 0.2159 # 輪胎尺寸 18 x 8.50–8.00 中的 8.50 是指寬度 8.50 英寸。8.50 英寸 * 0.0254 m/inch = 0.2159 m。
    wheel_base: 1.64 # YDRE 軸距 (Wheelbase) 64.6 英寸。64.6 英寸 * 0.0254 m/inch = 1.64084 m，四捨五入為 1.64 m。
    wheel_tread: 0.98 # YDRE 輪距 (Tread) 後輪 38.6 英寸。38.6 英寸 * 0.0254 m/inch = 0.98044 m，四捨五入為 0.98 m。請注意，YDRE 前輪距 34.3 英寸 (0.87 m)，後輪距 38.6 英寸 (0.98 m)。一般 `wheel_tread` 會取驅動輪或平均值。此處使用後輪距。
    front_overhang: 0.25 # YDRE 總長 93.4 英寸 (2.395 m)，軸距 64.6 英寸 (1.64 m)。前懸約為 (總長 - 軸距) / 2。若假設車輛中心在軸距中間，則前懸約為 (2.395 - 1.64) / 2 = 0.3775 m。但考慮到 `base_link` 通常設在後軸，前懸應為 總長 - 軸距 - 後懸。如果沒有具體後懸數據，通常會根據車輛結構估計。這裡給定一個估計值 0.75 m。
    rear_overhang: 0.25 # 假設 `base_link` 在後軸中心，則後懸應為 0。如果 `base_link` 在其他位置，則需要相應調整。
    left_overhang: 0.10 # YDRE 總寬 47.2 英寸 (1.2 m)。車輪寬度 8.50 英寸 (0.2159 m)。左右懸臂的計算需要考量車輛外緣與車輪中心線的距離。例如，(總寬 - 輪距) / 2 = (1.2 - 0.98) / 2 = 0.11 m。這個值是從輪胎外緣到車輛外緣的距離。如果此處 `left_overhang` 是指從中心線到最左邊的距離，那就是 總寬 / 2 = 1.2 / 2 = 0.6 m。
    right_overhang: 0.10 # 同上，為 總寬 / 2。
    vehicle_height: 2.5 # YDRE 總高 46.9 英寸。46.9 英寸 * 0.0254 m/inch = 1.19126 m，四捨五入為 1.19 m。
    max_steer_angle: 0.513 # [rad] 這通常指前輪的最大轉向角度。YDRE 轉向角度 1.85 圈是指方向盤轉向圈數。這個值需要透過車輛的轉向比來計算。如果沒有轉向比，0.70 rad (約 40 度) 是高爾夫球車常見的數值，您可以先保留。
